version: '3.8'

services:
  budgetit:
    build: .
    ports:
      - "3000:80"
    container_name: budgetit-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optionnel: monter un volume pour les logs
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Service de développement (optionnel)
  budgetit-dev:
    build: .
    ports:
      - "3001:80"
    container_name: budgetit-dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
    profiles:
      - dev 